import { createApp } from 'vue';
import { createPinia } from 'pinia';
import App from './App.vue';
import { installReliableKernelClientFeed } from './transport/reliableKernelFeed';
import 'katex/dist/katex.min.css';
import './theme/tokens.css';
import './theme/base.css';
import './theme/motion/message.css';
import './theme/motion/dialog.css';
import './theme/motion/dropdown.css';
import './theme/motion/collapse.css';
import './theme/motion/content.css';
import './theme/motion/composer.css';
import './theme/motion/status.css';

const app = createApp(App);
const pinia = createPinia();
app.use(pinia);
installReliableKernelClientFeed(pinia);
app.mount('#app');
