/* This file is generated by scripts/reliable-kernel/generate-physical-cutover-manifest.mjs. */

export type PhysicalCutoverDisposition = 'preserve-whole' | 'archive-reset-whole' | 'filter-by-scope' | 'preserve-in-place';

export interface PhysicalCutoverManifestEntry {
  readonly id: string;
  readonly relativePath: string;
  readonly disposition: PhysicalCutoverDisposition;
  readonly preservedScopeKinds?: readonly string[];
}

export interface PhysicalCutoverManifest {
  readonly contractRevision: string;
  readonly preserveWhole: readonly PhysicalCutoverManifestEntry[];
  readonly filterByScope: readonly PhysicalCutoverManifestEntry[];
  readonly archiveReset: readonly PhysicalCutoverManifestEntry[];
  readonly externalPreserve: readonly PhysicalCutoverManifestEntry[];
  readonly settingsSections: readonly PhysicalCutoverManifestEntry[];
  readonly conversationSettings: {
    readonly filePrefix: string;
    readonly fileSuffixes: readonly string[];
    readonly transactionRoot: string;
  };
  readonly rootPointerRelativePath: string;
}

export const PHYSICAL_CUTOVER_MANIFEST: PhysicalCutoverManifest = Object.freeze({
  "contractRevision": "2026-07-31-r4",
  "preserveWhole": [
    {
      "id": "root.agents",
      "relativePath": "agents",
      "disposition": "preserve-whole"
    },
    {
      "id": "root.checkpoint-policies",
      "relativePath": "checkpoint-policies",
      "disposition": "preserve-whole"
    },
    {
      "id": "root.model-profiles",
      "relativePath": "model-profiles",
      "disposition": "preserve-whole"
    },
    {
      "id": "root.plan-review-policies",
      "relativePath": "plan-review-policies",
      "disposition": "preserve-whole"
    },
    {
      "id": "root.runtime-contexts",
      "relativePath": "runtime-contexts",
      "disposition": "preserve-whole"
    },
    {
      "id": "root.skill-policies",
      "relativePath": "skill-policies",
      "disposition": "preserve-whole"
    },
    {
      "id": "root.system-prompts",
      "relativePath": "system-prompts",
      "disposition": "preserve-whole"
    },
    {
      "id": "root.tool-policies",
      "relativePath": "tool-policies",
      "disposition": "preserve-whole"
    },
    {
      "id": "root.work-environment-policies",
      "relativePath": "work-environment-policies",
      "disposition": "preserve-whole"
    },
    {
      "id": "root.work-environments",
      "relativePath": "work-environments",
      "disposition": "preserve-whole"
    },
    {
      "id": "root.workflows",
      "relativePath": "workflows",
      "disposition": "preserve-whole"
    }
  ],
  "filterByScope": [
    {
      "id": "root.checkpoint-policy-scope-links",
      "relativePath": "checkpoint-policy-scope-links",
      "disposition": "filter-by-scope",
      "preservedScopeKinds": [
        "global",
        "agent",
        "workflow"
      ]
    },
    {
      "id": "root.model-profile-scope-links",
      "relativePath": "model-profile-scope-links",
      "disposition": "filter-by-scope",
      "preservedScopeKinds": [
        "global",
        "agent",
        "workflow"
      ]
    },
    {
      "id": "root.plan-review-policy-scope-links",
      "relativePath": "plan-review-policy-scope-links",
      "disposition": "filter-by-scope",
      "preservedScopeKinds": [
        "global",
        "agent",
        "workflow"
      ]
    },
    {
      "id": "root.runtime-context-scope-links",
      "relativePath": "runtime-context-scope-links",
      "disposition": "filter-by-scope",
      "preservedScopeKinds": [
        "global",
        "agent",
        "workflow"
      ]
    },
    {
      "id": "root.settings",
      "relativePath": "settings",
      "disposition": "filter-by-scope",
      "preservedScopeKinds": [
        "global"
      ]
    },
    {
      "id": "root.skill-policy-scope-links",
      "relativePath": "skill-policy-scope-links",
      "disposition": "filter-by-scope",
      "preservedScopeKinds": [
        "global",
        "agent",
        "workflow"
      ]
    },
    {
      "id": "root.system-prompt-scope-links",
      "relativePath": "system-prompt-scope-links",
      "disposition": "filter-by-scope",
      "preservedScopeKinds": [
        "global",
        "agent",
        "workflow"
      ]
    },
    {
      "id": "root.tool-policy-scope-links",
      "relativePath": "tool-policy-scope-links",
      "disposition": "filter-by-scope",
      "preservedScopeKinds": [
        "global",
        "agent",
        "workflow"
      ]
    },
    {
      "id": "root.work-environment-policy-scope-links",
      "relativePath": "work-environment-policy-scope-links",
      "disposition": "filter-by-scope",
      "preservedScopeKinds": [
        "global",
        "agent",
        "workflow"
      ]
    }
  ],
  "archiveReset": [
    {
      "id": "control.data-reset-pending",
      "relativePath": ".limcode-data-reset-pending.json",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "file.data-root-marker",
      "relativePath": ".limcode-data-root.json",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.agent-answer-submission-links",
      "relativePath": "agent-answer-submission-links",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.agent-answer-target-links",
      "relativePath": "agent-answer-target-links",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.agent-answers",
      "relativePath": "agent-answers",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.agent-conversation-links",
      "relativePath": "agent-conversation-links",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.answer-bridge-links",
      "relativePath": "answer-bridge-links",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.attachments",
      "relativePath": "attachments",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.authority-derivation-links",
      "relativePath": "authority-derivation-links",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.authority-snapshots",
      "relativePath": "authority-snapshots",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.background-process-exit-receipts",
      "relativePath": "background-process-exit-receipts",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.background-process-notification-deliveries",
      "relativePath": "background-process-notification-deliveries",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.background-process-origin-links",
      "relativePath": "background-process-origin-links",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.background-processes",
      "relativePath": "background-processes",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.checkpoint-shadow-worktrees",
      "relativePath": "checkpoint-shadow-worktrees",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.checkpoint-timeline-anchors",
      "relativePath": "checkpoint-timeline-anchors",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.checkpoints",
      "relativePath": "checkpoints",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.child-turn-links",
      "relativePath": "child-turn-links",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.compression-block-llm-invocation-links",
      "relativePath": "compression-block-llm-invocation-links",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.compression-block-source-links",
      "relativePath": "compression-block-source-links",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.compression-blocks",
      "relativePath": "compression-blocks",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.compression-context-variants",
      "relativePath": "compression-context-variants",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.conversation-agent-selections",
      "relativePath": "conversation-agent-selections",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.conversation-checkpoint-repository-links",
      "relativePath": "conversation-checkpoint-repository-links",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.conversation-history",
      "relativePath": "conversation-history",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.conversation-project-links",
      "relativePath": "conversation-project-links",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.conversation-runtime-context-snapshot-links",
      "relativePath": "conversation-runtime-context-snapshot-links",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.conversation-work-environment-links",
      "relativePath": "conversation-work-environment-links",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.conversation-workflow-selections",
      "relativePath": "conversation-workflow-selections",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.conversations",
      "relativePath": "conversations",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.execution-leases",
      "relativePath": "execution-leases",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.interaction-owner-links",
      "relativePath": "interaction-owner-links",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.interaction-responses",
      "relativePath": "interaction-responses",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.interactions",
      "relativePath": "interactions",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.message-turn-links",
      "relativePath": "message-turn-links",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.operations",
      "relativePath": "operations",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.pending-turn-inputs",
      "relativePath": "pending-turn-inputs",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.project-contexts",
      "relativePath": "project-contexts",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.run-runtime-context-snapshot-links",
      "relativePath": "run-runtime-context-snapshot-links",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.run-work-environment-links",
      "relativePath": "run-work-environment-links",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.runtime-context-snapshots",
      "relativePath": "runtime-context-snapshots",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.runtime-delivery-links",
      "relativePath": "runtime-delivery-links",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.runtime-inbox-items",
      "relativePath": "runtime-inbox-items",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.shadow-repositories",
      "relativePath": "shadow-repositories",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.tool-call-events",
      "relativePath": "tool-call-events",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.tool-call-result-links",
      "relativePath": "tool-call-result-links",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.tool-calls",
      "relativePath": "tool-calls",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.tool-result-artifacts",
      "relativePath": "tool-result-artifacts",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.tool-result-blobs",
      "relativePath": "tool-result-blobs",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.turn-execution-preset-revisions",
      "relativePath": "turn-execution-preset-revisions",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.turn-intent-revisions",
      "relativePath": "turn-intent-revisions",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.turn-intents",
      "relativePath": "turn-intents",
      "disposition": "archive-reset-whole"
    },
    {
      "id": "root.turns",
      "relativePath": "turns",
      "disposition": "archive-reset-whole"
    }
  ],
  "externalPreserve": [
    {
      "id": "control.data-root-backups",
      "relativePath": ".limcode-data-backups",
      "disposition": "preserve-in-place"
    },
    {
      "id": "external.global-agents-rule",
      "relativePath": "AGENTS.md",
      "disposition": "preserve-in-place"
    },
    {
      "id": "external.global-claude-rule",
      "relativePath": "CLAUDE.md",
      "disposition": "preserve-in-place"
    },
    {
      "id": "external.global-skills",
      "relativePath": "skills",
      "disposition": "preserve-in-place"
    }
  ],
  "settingsSections": [
    {
      "id": "setting.llm",
      "relativePath": "llm.json",
      "disposition": "preserve-whole"
    },
    {
      "id": "setting.llmProviderConfigs",
      "relativePath": "llm-provider-configs",
      "disposition": "preserve-whole"
    },
    {
      "id": "setting.llmCompression",
      "relativePath": "llm-compression.json",
      "disposition": "preserve-whole"
    },
    {
      "id": "setting.llmCompressionConfigs",
      "relativePath": "llm-compression-configs",
      "disposition": "preserve-whole"
    },
    {
      "id": "setting.checkpointMaintenance",
      "relativePath": "checkpoint-maintenance.json",
      "disposition": "preserve-whole"
    },
    {
      "id": "setting.appearance",
      "relativePath": "appearance.json",
      "disposition": "preserve-whole"
    },
    {
      "id": "setting.attachments",
      "relativePath": "attachments.json",
      "disposition": "preserve-whole"
    },
    {
      "id": "setting.mcpServers",
      "relativePath": "mcp-servers",
      "disposition": "preserve-whole"
    }
  ],
  "conversationSettings": {
    "filePrefix": "conversation-",
    "fileSuffixes": [
      "-common.json",
      "-llm.json"
    ],
    "transactionRoot": ".conversation-settings-transactions"
  },
  "rootPointerRelativePath": "root-binding.json"
} as PhysicalCutoverManifest);
