import type { ConversationId } from '../../../shared/stableIds';
import type { DurableConversationFacts } from './types';

/** Canonical empty aggregate used by migration, creation and pure domain tests. */
export function emptyDurableConversationFacts(conversationId: ConversationId): DurableConversationFacts {
  return {
    conversation: { id: conversationId, visibility: 'visible', createdAt: 0, lastActivityAt: 0 },
    messages: [],
    messageRevisions: [],
    messageCurrentRevisionLinks: [],
    modelContextProjections: [],
    modelContextProjectionSourceLinks: [],
    requestModelContextProjectionLinks: [],
    compressionModelContextProjectionLinks: [],
    turns: [],
    turnIntents: [],
    turnIntentRevisions: [],
    turnExecutionPresetRevisions: [],
    pendingTurnInputs: [],
    executionLeases: [],
    authoritySnapshots: [],
    authorityDerivationLinks: [],
    runtimeInboxItems: [],
    runtimeDeliveryLinks: [],
    childTurnLinks: [],
    messageTurnLinks: [],
    interactionOwnerLinks: [],
    interactionResponses: [],
    runTerminations: [],
    runContextPolicies: [],
    runContextPolicyLinks: [],
    runSources: [],
    runTargets: [],
    toolRunLinks: [],
    inputRevisions: [],
    contextSnapshots: [],
    invocations: [],
    requests: [],
    toolCalls: [],
    toolCallEvents: [],
    toolResultArtifacts: [],
    toolCallResultLinks: [],
    toolExecutions: [],
    compressionBlocks: [],
    compressionBlockSourceLinks: [],
    compressionContextVariants: [],
    compressionBlockLlmInvocationLinks: [],
    runCompressionBlockLinks: [],
    projectContexts: [],
    shadowRepositories: [],
    conversationCheckpointRepositoryLinks: [],
    checkpoints: [],
    checkpointTimelineAnchors: [],
    operations: [],
    attempts: [],
    primaryEffects: [],
    effectPayloads: [],
    interactionRequests: [],
    pauses: [],
    operationResolutions: [],
    answerBridges: [],
    answerSubmissions: [],
    answerPayloads: [],
    streamCheckpointHeads: [],
    terminalStreamFences: []
  };
}
